// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package server

import (
	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
)

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// User defines model for User.
type User struct {
	Email    string             `json:"email"`
	Id       openapi_types.UUID `json:"id"`
	Username string             `json:"username"`
}

// UserUpdate defines model for UserUpdate.
type UserUpdate struct {
	Email    string `json:"email"`
	Username string `json:"username"`
}

// Users defines model for Users.
type Users = []User

// UserID defines model for UserID.
type UserID = openapi_types.UUID

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// InternalServerError defines model for InternalServerError.
type InternalServerError = Error

// NotFound defines model for NotFound.
type NotFound = Error

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = User

// UpdateUserByIdJSONRequestBody defines body for UpdateUserById for application/json ContentType.
type UpdateUserByIdJSONRequestBody = UserUpdate
